/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppSavedRouteImport } from './routes/_app/saved'
import { Route as AppProfileRouteImport } from './routes/_app/profile'
import { Route as AppHistoryRouteImport } from './routes/_app/history'
import { Route as AppScanIdRouteImport } from './routes/_app/scan.$id'
import { Route as AppPProductIdRouteImport } from './routes/_app/p.$productId'
import { Route as AppScanIdIndexRouteImport } from './routes/_app/scan.$id.index'
import { Route as ApiPublicHooksRunIngestionRouteImport } from './routes/api/public/hooks/run-ingestion'
import { Route as ApiPublicHooksIngestProductRouteImport } from './routes/api/public/hooks/ingest-product'
import { Route as ApiPublicHooksEnqueueVendorBackfillRouteImport } from './routes/api/public/hooks/enqueue-vendor-backfill'
import { Route as AppScanIdShareRouteImport } from './routes/_app/scan.$id.share'
import { Route as AppCommunityBrandProductRouteImport } from './routes/_app/community.$brand.$product'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppSavedRoute = AppSavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppHistoryRoute = AppHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AppRoute,
} as any)
const AppScanIdRoute = AppScanIdRouteImport.update({
  id: '/scan/$id',
  path: '/scan/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppPProductIdRoute = AppPProductIdRouteImport.update({
  id: '/p/$productId',
  path: '/p/$productId',
  getParentRoute: () => AppRoute,
} as any)
const AppScanIdIndexRoute = AppScanIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppScanIdRoute,
} as any)
const ApiPublicHooksRunIngestionRoute =
  ApiPublicHooksRunIngestionRouteImport.update({
    id: '/api/public/hooks/run-ingestion',
    path: '/api/public/hooks/run-ingestion',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksIngestProductRoute =
  ApiPublicHooksIngestProductRouteImport.update({
    id: '/api/public/hooks/ingest-product',
    path: '/api/public/hooks/ingest-product',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksEnqueueVendorBackfillRoute =
  ApiPublicHooksEnqueueVendorBackfillRouteImport.update({
    id: '/api/public/hooks/enqueue-vendor-backfill',
    path: '/api/public/hooks/enqueue-vendor-backfill',
    getParentRoute: () => rootRouteImport,
  } as any)
const AppScanIdShareRoute = AppScanIdShareRouteImport.update({
  id: '/share',
  path: '/share',
  getParentRoute: () => AppScanIdRoute,
} as any)
const AppCommunityBrandProductRoute =
  AppCommunityBrandProductRouteImport.update({
    id: '/community/$brand/$product',
    path: '/community/$brand/$product',
    getParentRoute: () => AppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/history': typeof AppHistoryRoute
  '/profile': typeof AppProfileRoute
  '/saved': typeof AppSavedRoute
  '/p/$productId': typeof AppPProductIdRoute
  '/scan/$id': typeof AppScanIdRouteWithChildren
  '/community/$brand/$product': typeof AppCommunityBrandProductRoute
  '/scan/$id/share': typeof AppScanIdShareRoute
  '/api/public/hooks/enqueue-vendor-backfill': typeof ApiPublicHooksEnqueueVendorBackfillRoute
  '/api/public/hooks/ingest-product': typeof ApiPublicHooksIngestProductRoute
  '/api/public/hooks/run-ingestion': typeof ApiPublicHooksRunIngestionRoute
  '/scan/$id/': typeof AppScanIdIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/history': typeof AppHistoryRoute
  '/profile': typeof AppProfileRoute
  '/saved': typeof AppSavedRoute
  '/': typeof AppIndexRoute
  '/p/$productId': typeof AppPProductIdRoute
  '/community/$brand/$product': typeof AppCommunityBrandProductRoute
  '/scan/$id/share': typeof AppScanIdShareRoute
  '/api/public/hooks/enqueue-vendor-backfill': typeof ApiPublicHooksEnqueueVendorBackfillRoute
  '/api/public/hooks/ingest-product': typeof ApiPublicHooksIngestProductRoute
  '/api/public/hooks/run-ingestion': typeof ApiPublicHooksRunIngestionRoute
  '/scan/$id': typeof AppScanIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/history': typeof AppHistoryRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/saved': typeof AppSavedRoute
  '/_app/': typeof AppIndexRoute
  '/_app/p/$productId': typeof AppPProductIdRoute
  '/_app/scan/$id': typeof AppScanIdRouteWithChildren
  '/_app/community/$brand/$product': typeof AppCommunityBrandProductRoute
  '/_app/scan/$id/share': typeof AppScanIdShareRoute
  '/api/public/hooks/enqueue-vendor-backfill': typeof ApiPublicHooksEnqueueVendorBackfillRoute
  '/api/public/hooks/ingest-product': typeof ApiPublicHooksIngestProductRoute
  '/api/public/hooks/run-ingestion': typeof ApiPublicHooksRunIngestionRoute
  '/_app/scan/$id/': typeof AppScanIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/history'
    | '/profile'
    | '/saved'
    | '/p/$productId'
    | '/scan/$id'
    | '/community/$brand/$product'
    | '/scan/$id/share'
    | '/api/public/hooks/enqueue-vendor-backfill'
    | '/api/public/hooks/ingest-product'
    | '/api/public/hooks/run-ingestion'
    | '/scan/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/history'
    | '/profile'
    | '/saved'
    | '/'
    | '/p/$productId'
    | '/community/$brand/$product'
    | '/scan/$id/share'
    | '/api/public/hooks/enqueue-vendor-backfill'
    | '/api/public/hooks/ingest-product'
    | '/api/public/hooks/run-ingestion'
    | '/scan/$id'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/_app/history'
    | '/_app/profile'
    | '/_app/saved'
    | '/_app/'
    | '/_app/p/$productId'
    | '/_app/scan/$id'
    | '/_app/community/$brand/$product'
    | '/_app/scan/$id/share'
    | '/api/public/hooks/enqueue-vendor-backfill'
    | '/api/public/hooks/ingest-product'
    | '/api/public/hooks/run-ingestion'
    | '/_app/scan/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiPublicHooksEnqueueVendorBackfillRoute: typeof ApiPublicHooksEnqueueVendorBackfillRoute
  ApiPublicHooksIngestProductRoute: typeof ApiPublicHooksIngestProductRoute
  ApiPublicHooksRunIngestionRoute: typeof ApiPublicHooksRunIngestionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/saved': {
      id: '/_app/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof AppSavedRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/history': {
      id: '/_app/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof AppHistoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/scan/$id': {
      id: '/_app/scan/$id'
      path: '/scan/$id'
      fullPath: '/scan/$id'
      preLoaderRoute: typeof AppScanIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/p/$productId': {
      id: '/_app/p/$productId'
      path: '/p/$productId'
      fullPath: '/p/$productId'
      preLoaderRoute: typeof AppPProductIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/scan/$id/': {
      id: '/_app/scan/$id/'
      path: '/'
      fullPath: '/scan/$id/'
      preLoaderRoute: typeof AppScanIdIndexRouteImport
      parentRoute: typeof AppScanIdRoute
    }
    '/api/public/hooks/run-ingestion': {
      id: '/api/public/hooks/run-ingestion'
      path: '/api/public/hooks/run-ingestion'
      fullPath: '/api/public/hooks/run-ingestion'
      preLoaderRoute: typeof ApiPublicHooksRunIngestionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/ingest-product': {
      id: '/api/public/hooks/ingest-product'
      path: '/api/public/hooks/ingest-product'
      fullPath: '/api/public/hooks/ingest-product'
      preLoaderRoute: typeof ApiPublicHooksIngestProductRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/enqueue-vendor-backfill': {
      id: '/api/public/hooks/enqueue-vendor-backfill'
      path: '/api/public/hooks/enqueue-vendor-backfill'
      fullPath: '/api/public/hooks/enqueue-vendor-backfill'
      preLoaderRoute: typeof ApiPublicHooksEnqueueVendorBackfillRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/scan/$id/share': {
      id: '/_app/scan/$id/share'
      path: '/share'
      fullPath: '/scan/$id/share'
      preLoaderRoute: typeof AppScanIdShareRouteImport
      parentRoute: typeof AppScanIdRoute
    }
    '/_app/community/$brand/$product': {
      id: '/_app/community/$brand/$product'
      path: '/community/$brand/$product'
      fullPath: '/community/$brand/$product'
      preLoaderRoute: typeof AppCommunityBrandProductRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppScanIdRouteChildren {
  AppScanIdShareRoute: typeof AppScanIdShareRoute
  AppScanIdIndexRoute: typeof AppScanIdIndexRoute
}

const AppScanIdRouteChildren: AppScanIdRouteChildren = {
  AppScanIdShareRoute: AppScanIdShareRoute,
  AppScanIdIndexRoute: AppScanIdIndexRoute,
}

const AppScanIdRouteWithChildren = AppScanIdRoute._addFileChildren(
  AppScanIdRouteChildren,
)

interface AppRouteChildren {
  AppHistoryRoute: typeof AppHistoryRoute
  AppProfileRoute: typeof AppProfileRoute
  AppSavedRoute: typeof AppSavedRoute
  AppIndexRoute: typeof AppIndexRoute
  AppPProductIdRoute: typeof AppPProductIdRoute
  AppScanIdRoute: typeof AppScanIdRouteWithChildren
  AppCommunityBrandProductRoute: typeof AppCommunityBrandProductRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppHistoryRoute: AppHistoryRoute,
  AppProfileRoute: AppProfileRoute,
  AppSavedRoute: AppSavedRoute,
  AppIndexRoute: AppIndexRoute,
  AppPProductIdRoute: AppPProductIdRoute,
  AppScanIdRoute: AppScanIdRouteWithChildren,
  AppCommunityBrandProductRoute: AppCommunityBrandProductRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiPublicHooksEnqueueVendorBackfillRoute:
    ApiPublicHooksEnqueueVendorBackfillRoute,
  ApiPublicHooksIngestProductRoute: ApiPublicHooksIngestProductRoute,
  ApiPublicHooksRunIngestionRoute: ApiPublicHooksRunIngestionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
